/**
 * Sparks OpenAPI
 * Generated documentation for the Logicdrop Sparks API and OpenAPI clients.  Logicdrop Sparks lets users build rules, analyze data, and automate documents.  Use it to make decisions faster, generate documents better, and learn from your data.  ### Documentation - [User Documentation](https://docs.logicdrop.com)  ### Modules - [Sparks Compute](https://docs.logicdrop.com/rules/introduction) - [Sparks Decision Tables](https://docs.logicdrop.com/rules/authoring-decision-tables) - [Sparks Documents](https://docs.logicdrop.com/documents/introduction)  ### Clients - [OpenAPI Clients](https://docs.logicdrop.com/development/sample-clients)  ### Security - [Authorizing API Requests](https://docs.logicdrop.com/development/authorization) 
 *
 * The version of the OpenAPI document: v_VERSION_._BUILD_
 * Contact: support@logicdrop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "../api";

export class ComputeRule {
    'id'?: string;
    'name'?: string;
    'client'?: string;
    'project'?: string;
    'version'?: string;
    'build'?: number;
    'url'?: string;
    'agendaGroup'?: string;
    'activationGroup'?: string;
    'ruleflowGroup'?: string;
    'noLoop'?: boolean;
    'lockOnActive'?: boolean;
    'enabled'?: boolean;
    'log'?: boolean;
    'ruleset'?: string;
    'description'?: string;
    'created'?: Date;
    'modified'?: Date;
    'tags'?: Array<string>;
    'properties'?: { [key: string]: object; };
    'salience'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "client",
            "baseName": "client",
            "type": "string"
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "build",
            "baseName": "build",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "agendaGroup",
            "baseName": "agendaGroup",
            "type": "string"
        },
        {
            "name": "activationGroup",
            "baseName": "activationGroup",
            "type": "string"
        },
        {
            "name": "ruleflowGroup",
            "baseName": "ruleflowGroup",
            "type": "string"
        },
        {
            "name": "noLoop",
            "baseName": "noLoop",
            "type": "boolean"
        },
        {
            "name": "lockOnActive",
            "baseName": "lockOnActive",
            "type": "boolean"
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        },
        {
            "name": "log",
            "baseName": "log",
            "type": "boolean"
        },
        {
            "name": "ruleset",
            "baseName": "ruleset",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "modified",
            "baseName": "modified",
            "type": "Date"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "salience",
            "baseName": "salience",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ComputeRule.attributeTypeMap;
    }
}

