/**
 * Sparks OpenAPI
 * Generated documentation for the Logicdrop Sparks API and OpenAPI clients.  Logicdrop Sparks lets users build rules, analyze data, and automate documents.  Use it to make decisions faster, generate documents better, and learn from your data.  ### Documentation - [User Documentation](https://docs.logicdrop.com)  ### Modules - [Sparks Compute](https://docs.logicdrop.com/rules/introduction) - [Sparks Decision Tables](https://docs.logicdrop.com/rules/authoring-decision-tables) - [Sparks Documents](https://docs.logicdrop.com/documents/introduction)  ### Clients - [OpenAPI Clients](https://docs.logicdrop.com/development/sample-clients)  ### Security - [Authorizing API Requests](https://docs.logicdrop.com/development/authorization) 
 *
 * The version of the OpenAPI document: v_VERSION_, build# _BUILD_
 * Contact: support@logicdrop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "../api";

export class ContainerResponse {
    /**
    * Display name
    */
    'display'?: string;
    /**
    * Description
    */
    'description'?: string;
    /**
    * Client name
    */
    'client'?: string;
    /**
    * Project name
    */
    'project'?: string;
    /**
    * Ruleset name
    */
    'ruleset'?: string;
    /**
    * Version
    */
    'version'?: string;
    /**
    * Total running time
    */
    'uptime'?: string;
    /**
    * Status of the container
    */
    'status'?: ContainerResponse.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "display",
            "baseName": "display",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "client",
            "baseName": "client",
            "type": "string"
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "string"
        },
        {
            "name": "ruleset",
            "baseName": "ruleset",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "uptime",
            "baseName": "uptime",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ContainerResponse.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return ContainerResponse.attributeTypeMap;
    }
}

export namespace ContainerResponse {
    export enum StatusEnum {
        RUNNING = <any> 'RUNNING',
        STOPPED = <any> 'STOPPED',
        ERROR = <any> 'ERROR'
    }
}
