/**
 * Sparks OpenAPI
 * Generated documentation for the Logicdrop Sparks API and OpenAPI clients.  Logicdrop Sparks lets users build rules, analyze data, and automate documents.  Use it to make decisions faster, generate documents better, and learn from your data.  ### Documentation - [User Documentation](https://docs.logicdrop.com)  ### Modules - [Sparks Compute](https://docs.logicdrop.com/rules/introduction) - [Sparks Decision Tables](https://docs.logicdrop.com/rules/authoring-decision-tables) - [Sparks Documents](https://docs.logicdrop.com/documents/introduction)  ### Clients - [OpenAPI Clients](https://docs.logicdrop.com/development/sample-clients)  ### Security - [Authorizing API Requests](https://docs.logicdrop.com/development/authorization) 
 *
 * The version of the OpenAPI document: v_VERSION_, build# _BUILD_
 * Contact: support@logicdrop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "../api";

/**
* Designer options
*/
export class DesignerOptions {
    /**
    * Enable debugging?
    */
    'debug'?: boolean;
    /**
    * Maximum rules to fire
    */
    'threshold'?: number;
    /**
    * Include ruleset content?
    */
    'content'?: boolean;
    /**
    * Enable event tracing?
    */
    'tracing'?: boolean;
    /**
    * Expand data in events?
    */
    'expand'?: boolean;
    /**
    * Include flattened data
    */
    'dictionary'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "debug",
            "baseName": "debug",
            "type": "boolean"
        },
        {
            "name": "threshold",
            "baseName": "threshold",
            "type": "number"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "boolean"
        },
        {
            "name": "tracing",
            "baseName": "tracing",
            "type": "boolean"
        },
        {
            "name": "expand",
            "baseName": "expand",
            "type": "boolean"
        },
        {
            "name": "dictionary",
            "baseName": "dictionary",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return DesignerOptions.attributeTypeMap;
    }
}

