/**
 * Sparks OpenAPI
 * Generated documentation for the Logicdrop Sparks API and OpenAPI clients.  Logicdrop Sparks lets users build rules, analyze data, and automate documents.  Use it to make decisions faster, generate documents better, and learn from your data.  ### Documentation - [User Documentation](https://docs.logicdrop.com)  ### Modules - [Sparks Compute](https://docs.logicdrop.com/rules/introduction) - [Sparks Decision Tables](https://docs.logicdrop.com/rules/authoring-decision-tables) - [Sparks Documents](https://docs.logicdrop.com/documents/introduction)  ### Clients - [OpenAPI Clients](https://docs.logicdrop.com/development/sample-clients)  ### Security - [Authorizing API Requests](https://docs.logicdrop.com/development/authorization) 
 *
 * The version of the OpenAPI document: v_VERSION_._BUILD_
 * Contact: support@logicdrop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RuleEventData } from './ruleEventData';
import { RequestFile } from "../api";

/**
* Events
*/
export class DesignerEvent {
    /**
    * Event type
    */
    'event'?: DesignerEvent.EventEnum;
    /**
    * Rule type
    */
    'type'?: string;
    /**
    * Event message
    */
    'message'?: string;
    /**
    * Rule name
    */
    'rule'?: string;
    /**
    * Rule path
    */
    'path'?: string;
    /**
    * User rule name
    */
    'name'?: string;
    /**
    * User rule source
    */
    'source'?: string;
    /**
    * User rule row (if applicable)
    */
    'row'?: number;
    /**
    * Rule Id
    */
    'id'?: string;
    /**
    * Timestamp
    */
    'timestamp'?: number;
    /**
    * Match triggers
    */
    'triggers'?: Array<object>;
    'current'?: RuleEventData;
    'previous'?: RuleEventData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "event",
            "baseName": "event",
            "type": "DesignerEvent.EventEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "rule",
            "baseName": "rule",
            "type": "string"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string"
        },
        {
            "name": "row",
            "baseName": "row",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "triggers",
            "baseName": "triggers",
            "type": "Array<object>"
        },
        {
            "name": "current",
            "baseName": "current",
            "type": "RuleEventData"
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "RuleEventData"
        }    ];

    static getAttributeTypeMap() {
        return DesignerEvent.attributeTypeMap;
    }
}

export namespace DesignerEvent {
    export enum EventEnum {
        INSERT = <any> 'INSERT',
        DELETE = <any> 'DELETE',
        UPDATE = <any> 'UPDATE',
        BEFOREMATCH = <any> 'BEFORE_MATCH',
        AFTERMATCH = <any> 'AFTER_MATCH',
        MATCHCREATED = <any> 'MATCH_CREATED',
        MATCHCANCELLED = <any> 'MATCH_CANCELLED'
    }
}
