/**
 * Sparks OpenAPI
 * Generated documentation for the Logicdrop Sparks API and OpenAPI clients.  Logicdrop Sparks lets users build rules, analyze data, and automate documents.  Use it to make decisions faster, generate documents better, and learn from your data.  ### Documentation - [User Documentation](https://docs.logicdrop.com)  ### Modules - [Sparks Compute](https://docs.logicdrop.com/rules/introduction) - [Sparks Decision Tables](https://docs.logicdrop.com/rules/authoring-decision-tables) - [Sparks Documents](https://docs.logicdrop.com/documents/introduction)  ### Clients - [OpenAPI Clients](https://docs.logicdrop.com/development/sample-clients)  ### Security - [Authorizing API Requests](https://docs.logicdrop.com/development/authorization) 
 *
 * The version of the OpenAPI document: v_VERSION_, build# _BUILD_
 * Contact: support@logicdrop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "../api";

export class Field {
    'name'?: string;
    'display'?: string;
    'description'?: string;
    'defaultValue'?: object;
    'format'?: string;
    'type'?: Field.TypeEnum;
    'mode'?: Field.ModeEnum;
    'mapping'?: string;
    'order'?: number;
    'key'?: boolean;
    'index'?: boolean;
    'enabled'?: boolean;
    'visible'?: boolean;
    'required'?: boolean;
    'min'?: number;
    'max'?: number;
    'properties'?: { [key: string]: object; };
    'children'?: Array<Field>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "display",
            "baseName": "display",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "defaultValue",
            "baseName": "defaultValue",
            "type": "object"
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Field.TypeEnum"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "Field.ModeEnum"
        },
        {
            "name": "mapping",
            "baseName": "mapping",
            "type": "string"
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "number"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "boolean"
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "boolean"
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        },
        {
            "name": "visible",
            "baseName": "visible",
            "type": "boolean"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean"
        },
        {
            "name": "min",
            "baseName": "min",
            "type": "number"
        },
        {
            "name": "max",
            "baseName": "max",
            "type": "number"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "children",
            "baseName": "children",
            "type": "Array<Field>"
        }    ];

    static getAttributeTypeMap() {
        return Field.attributeTypeMap;
    }
}

export namespace Field {
    export enum TypeEnum {
        STRING = <any> 'STRING',
        INTEGER = <any> 'INTEGER',
        DOUBLE = <any> 'DOUBLE',
        DECIMAL = <any> 'DECIMAL',
        BOOLEAN = <any> 'BOOLEAN',
        OBJECT = <any> 'OBJECT',
        DATE = <any> 'DATE',
        DATETIME = <any> 'DATE_TIME',
        TIME = <any> 'TIME',
        LIST = <any> 'LIST',
        SET = <any> 'SET',
        MAP = <any> 'MAP'
    }
    export enum ModeEnum {
        READONLY = <any> 'READ_ONLY',
        READWRITE = <any> 'READ_WRITE',
        WRITEONLY = <any> 'WRITE_ONLY'
    }
}
